version: '3'
services:
  db:
    image: mongo
    ports: 
      - "27017:27017"
    restart: on-failure
  app:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on: 
      - "db"
    restart: on-failure
  front:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on: 
      - "db"
      - "app"
    restart: on-failure
  
  